---
  file:            # string
  sort:            avg # max|min|avg|sum|count|uri|method|max-body|min-body|avg-body|sum-body|p1|p50|p99|stddev
  reverse:         true # boolean
  query_string:    # boolean
  format:          # string
  limit:           # 5000
  noheaders:       # boolean
  show_footers:    # boolean
  filters:         # string
  output:          # string(comma separated)
  pos_file:        # string
  nosave_pos:      # boolean
  ltsv:
    apptime_label: # apptime
    status_label:  # status code
    size_label:    # size
    method_label:  # method
    uri_label:     # uri
    time_label:     # time
  json:
    uri_key:           # string
    method_key:        # string
    time_key:          # string
    response_time_key: # string
    body_bytes_key:    # string
    status_key:        # string
  regexp:
    pattern:              # string
    uri_subexp:           # string
    method_subexp:        # string
    time_subexp:          # string
    response_time_subexp: # string
    body_bytes_subexp:    # string
    status_subexp:        # string
  matching_groups:
    - /images/chair/.+
    - /api/estate/nazotte
    - /api/estate/search/condition
    - /api/estate/search
    - /api/estate/low_priced
    - /api/estate/req_doc/.+
    - /api/estate/[0-9]+
    - /api/chair/[0-9]+
    - /api/chair/buy/[0-9]+
    - /api/recommended_estate/.+
    - /images/.+
    - /_next/.+
